# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7749a3c72cb202cdb9cb79986e488aba9bbf47ae191d1ab7b30f76eb16e01febc6c1211bcdd830d772fb8a2a9f3bc51006fb14e3982fecadf730b86e254639db

test:
  secret_key_base: 364cb682a1171e06f76b5f5d0386b886815b199111877d12682a33f97f4a767caf27d724c379385bd6ec71cb7730a93083c11a9553a2a6c640b2d9e9517c10b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
